version: '3.8'

services:
    db:
      container_name: full-stack-db
      image: postgres
      restart: always
      ports: 
        - "5432:5432"
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: full-stack
      volumes:
        - .:/usr/app
      networks:
        - api-network

    api:
        container_name: full-stack-api
        image: full-stack-api-dev:1.0.0
        build: .
        command: yarn api start:dev
        ports:
            - 3000:3000
        depends_on:
          - db
        volumes:
            - .:/usr/app
        networks:
          - api-network
          
networks:
  api-network: